# Uncomment the next line to define a global platform for your project
# platform :ios, '10.2'

target 'Client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git', :tag => '0.9.26'

  target 'ClientTests' do
    inherit! :search_paths
    pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git', :tag => '0.9.26'

  end
end
